=pod
=head1 How to setup Dist::Zilla

=head2 Install

  cpanm Dist::Zilla

=head2 Set up global config

  dzil setup
  //Answer some questions.

=head2 Checkout dzil profiles

  cd ~/.dzil
  git clone git@github.com:kuzuha/p5-dzil-profiles.git profiles

=head2 Create a module

  //in your workspace
  dzil new Example::ModuleName
  cd Example-ModuleName
  
  //only need at first time
  dzil authordeps | cpanm

=head2 Those are all

  okay, all steps were done ;)
